### PR TITLE
Translate module Organizations

### PR DESCRIPTION
**Pull request by Cesarfr**
* This patches adds selectable languages to the Organizations module.
* Fixed stylesheets.
* All visible strings in the files PHP were translated also the JavaScript strings.
* Changed charset 'latin1' to 'utf8' in the database to future news languages.
* All updates are merged in this repository to add the new features (v1.3).
* Added script to change the database charset to utf8 in an existing installation.

Equally in this patch there is a dropdown where you can change the language dynamically. The language by default is English, but you can change the language to French.

## Screenshots
This module should look as follows:

### Dropdown
drop

### Home
**English**
org_home-en

**French**
org_home-fr

### New organization
**English**
org_addno-en

**French**
org_addno-fr

### Information of an organization
**English**
org_info-en

**French**
org_info-fr

### JavaScript
**English**
org_js-en

**French**
org_js-fr

To know more about what translation and internationalization are and how they work, see this page on the wiki: [Translation of ERMS CORAL](https://github.com/ndlibersa/CORAL-Main/wiki/Translation-of-ERMS-CORAL).

### CODE REVIEW

**Comment by remocrevo** [comment]
This probably needs an upgrade script also, to allow current CORAL installations to upgrade from Latin1 database tables to UTF-8. The upgrade script should be careful to convert any special characters so they are properly encoded after the upgrade.

**Comment by Cesarfr** [comment]
Hello @remocrevo, it's true, I'll work in this update because is very important, thanks

**Comment by Cesarfr** [comment]
Hi @remocrevo , I added changes in this pull request:

* Script SQL and manual 
* Fixed issues to add new languages

Please, if you can test this pull request, thanks.

**Comment by remocrevo** [comment]
After merging the form validation code, this branch has conflicts that need to be resolved.

**Comment by remocrevo** [comment]
Also, a previous branch removed "_DATABASE_NAME_" from all install scripts, and it looks like this code still has that prefix in some places, including the new upgrade script (update_latin1-to-utf8.sql).

**Pull request merged**
