### PR TITLE
Fixed issue #21 'Not validated forms'

### PR DESCRIPTION
**Pull request by Cesarfr**
Hello, I fixed the issue #21 , I validated the most important fields for each form, these are the forms validated:

* Contact form (add/edit)
* Account form (add/edit)
* Issues form (add/edit)
* Admin forms (edit)

### Contact form
**Add a contact**
org-addcont
**Update a contact**
org-updcont

### Account form
**Add an account**
org-addlogin
**Update an account**
org-updlogin

### Issues form
**Add an issue**
org-addissue
**Edit an issue**
org-updissue

Thanks.

### CODE REVIEW

**Comment by coraladmin** [comment]
@Cesarfr Not all contacts have a name. What if all I am trying to do is record an email address contact? Perhaps a general one for a publisher and don't want to enter anything else. I'm not sure a name should be required? What do others think?

**Comment by coraladmin** [comment]
All, is a username always required for an account. What if my email is the username, this will require you to put the email in the username field for anyone who has just been using the email field. Is this a concern for anyone?

**Comment by Cesarfr** [comment]
Hello @coraladmin , thanks for the observation, I think the name is required to avoid some problems to contact a person which uses the same email to another person. It is rare, but it can exist.

**Comment by PaulPoulain** [comment]
What about making "name or email" mandatory ?

**Comment by remocrevo** [comment]
This branch doesn't change the behavior of the Contact form. Name is already required. So if that is a concern, a new issue should be created.

As for requiring "Username" on the Accounts form, I think it would encourage "good practice", since it is important to be very clear when telling someone what values to use for logging in, and a blank "Username" would be unclear. My staff often need to enter the same value for "Username" and "Local Account Email", but I think it is worth the little extra effort to make the data more clear. And if a site wants to leave the "Local Account Email" blank whenever the username is the same, the form still allows that.

We have one case that doesn't require a username or password, which required us to enter "NONE" for both. Does anyone think we should remove validation on the username/password fields because of that possibility?

**Comment by ehartnett** [comment]
@Cesarfr I agree with @coraladmin that not all contacts have a name. There are often cases where all we have are a support email or phone number. It's a general contact like support@company.com. We don't have a name to go with it.

**Comment by remocrevo** [comment]
I merged this manually, with a slight correction to some of the validation messages. Thanks @Cesarfr, and thanks others for your input.  If anyone still thinks we need to stop requiring a contact name, they should open a new issue about that.

**Comment by ehartnett** [comment]
@remocrevo I believe we are up-to-date and I'm not seeing that contact name is required - I just test it now without a name and the only requirement was the role. It'll be disappointing if it is requiring a contact name now.

**Comment by remocrevo** [comment]
@ehartnett You are right! Now that I look closer, this branch does change the behavior, but only because the code previously only validated the Contact Name field after checking an obsolete "contactType" field, which was removed in 2011.  So this commit uncovers the Contact Name validation code.  Consensus seems to be that name shouldn't be required, so I'll re-open this pull request until I can fix it.

**Comment by remocrevo** [comment]
I pushed another commit that removes the Contact Name requirement.

**Pull request closed without merging**
